const mongoose = require("mongoose");
const db = require("./models");

// This file empties the Books collection and inserts the books below

mongoose.connect(
  process.env.MONGODB_URI ||
  "mongodb://localhost/cribsmack"
);

const gameCardSeed = [
    {
    gameid:"1",
    date: 12-31-82,
    userOne: "Dan",
    userTwo: "Chris",
    userOnePlayAvg:3,
    userOneCountAvg:7,
    userOneCribAvg:3.35,
    userTwoPlayAvg:3,
    userTwoCountAvg:7,
    userTwoCribAvg:3.35,
    hands:[
        {
            userOnePlay:1,
            userOneCount:5,
            userOneCrib:2,
            userOneTotal:8,
            userTwoPlay:0,
            userTwoCount:7,
            userTwoCrib:0,
            userTwoTotal:7
        },
        {
            userOnePlay:1,
            userOneCount:5,
            userOneCrib:2,
            userOneTotal:8,
            userTwoPlay:0,
            userTwoCount:7,
            userTwoCrib:0,
            userTwoTotal:7
        },
        {
            userOnePlay:1,
            userOneCount:5,
            userOneCrib:2,
            userOneTotal:8,
            userTwoPlay:0,
            userTwoCount:7,
            userTwoCrib:0,
            userTwoTotal:7
        },
        {
            userOnePlay:1,
            userOneCount:5,
            userOneCrib:2,
            userOneTotal:8,
            userTwoPlay:0,
            userTwoCount:7,
            userTwoCrib:0,
            userTwoTotal:7
        },
        {
            userOnePlay:1,
            userOneCount:5,
            userOneCrib:2,
            userOneTotal:8,
            userTwoPlay:0,
            userTwoCount:7,
            userTwoCrib:0,
            userTwoTotal:7
        },
        {
            userOnePlay:1,
            userOneCount:5,
            userOneCrib:2,
            userOneTotal:8,
            userTwoPlay:0,
            userTwoCount:7,
            userTwoCrib:0,
            userTwoTotal:7
        },
        {
            userOnePlay:1,
            userOneCount:5,
            userOneCrib:2,
            userOneTotal:8,
            userTwoPlay:0,
            userTwoCount:7,
            userTwoCrib:0,
            userTwoTotal:7
        },
        {
            userOnePlay:1,
            userOneCount:5,
            userOneCrib:2,
            userOneTotal:8,
            userTwoPlay:0,
            userTwoCount:7,
            userTwoCrib:0,
            userTwoTotal:7
        },
        {
            userOnePlay:1,
            userOneCount:5,
            userOneCrib:2,
            userOneTotal:8,
            userTwoPlay:0,
            userTwoCount:7,
            userTwoCrib:0,
            userTwoTotal:7
        }]
    },
        {
        gameid:"2",
        date: 12-31-82,
        userOne: "Rogelio",
        userTwo: "Eric",
        userOnePlayAvg:3,
        userOneCountAvg:7,
        userOneCribAvg:3.35,
        userTwoPlayAvg:3,
        userTwoCountAvg:7,
        userTwoCribAvg:3.35,
        hands:[
            {
            userOnePlay:1,
            userOneCount:5,
            userOneCrib:2,
            userOneTotal:8,
            userTwoPlay:0,
            userTwoCount:7,
            userTwoCrib:0,
            userTwoTotal:7
        },
        {
            userOnePlay:1,
            userOneCount:5,
            userOneCrib:2,
            userOneTotal:8,
            userTwoPlay:0,
            userTwoCount:7,
            userTwoCrib:0,
            userTwoTotal:7
        },
        {
            userOnePlay:1,
            userOneCount:5,
            userOneCrib:2,
            userOneTotal:8,
            userTwoPlay:0,
            userTwoCount:7,
            userTwoCrib:0,
            userTwoTotal:7
        },
        {
            userOnePlay:1,
            userOneCount:5,
            userOneCrib:2,
            userOneTotal:8,
            userTwoPlay:0,
            userTwoCount:7,
            userTwoCrib:0,
            userTwoTotal:7
        },
        {
            userOnePlay:1,
            userOneCount:5,
            userOneCrib:2,
            userOneTotal:8,
            userTwoPlay:0,
            userTwoCount:7,
            userTwoCrib:0,
            userTwoTotal:7
        },
        {
            userOnePlay:1,
            userOneCount:5,
            userOneCrib:2,
            userOneTotal:8,
            userTwoPlay:0,
            userTwoCount:7,
            userTwoCrib:0,
            userTwoTotal:7
        },
        {
            userOnePlay:1,
            userOneCount:5,
            userOneCrib:2,
            userOneTotal:8,
            userTwoPlay:0,
            userTwoCount:7,
            userTwoCrib:0,
            userTwoTotal:7
        },
        {
            userOnePlay:1,
            userOneCount:5,
            userOneCrib:2,
            userOneTotal:8,
            userTwoPlay:0,
            userTwoCount:7,
            userTwoCrib:0,
            userTwoTotal:7
        },
        {
            userOnePlay:1,
            userOneCount:5,
            userOneCrib:2,
            userOneTotal:8,
            userTwoPlay:0,
            userTwoCount:7,
            userTwoCrib:0,
            userTwoTotal:7
        }]
    },
        {
        gameid:"3",
        date: 12-31-82,
        userOne: "Maninatee",
        userTwo: "Sealor",
        userOnePlayAvg:3,
        userOneCountAvg:7,
        userOneCribAvg:3.35,
        userTwoPlayAvg:3,
        userTwoCountAvg:7,
        userTwoCribAvg:3.35,
        hands:[
            {
                userOnePlay:1,
                userOneCount:5,
                userOneCrib:2,
                userOneTotal:8,
                userTwoPlay:0,
                userTwoCount:7,
                userTwoCrib:0,
                userTwoTotal:7
            },
            {
                userOnePlay:1,
                userOneCount:5,
                userOneCrib:2,
                userOneTotal:8,
                userTwoPlay:0,
                userTwoCount:7,
                userTwoCrib:0,
                userTwoTotal:7
            },
            {
                userOnePlay:1,
                userOneCount:5,
                userOneCrib:2,
                userOneTotal:8,
                userTwoPlay:0,
                userTwoCount:7,
                userTwoCrib:0,
                userTwoTotal:7
            },
            {
                userOnePlay:1,
                userOneCount:5,
                userOneCrib:2,
                userOneTotal:8,
                userTwoPlay:0,
                userTwoCount:7,
                userTwoCrib:0,
                userTwoTotal:7
            },
            {
                userOnePlay:1,
                userOneCount:5,
                userOneCrib:2,
                userOneTotal:8,
                userTwoPlay:0,
                userTwoCount:7,
                userTwoCrib:0,
                userTwoTotal:7
            },
            {
                userOnePlay:1,
                userOneCount:5,
                userOneCrib:2,
                userOneTotal:8,
                userTwoPlay:0,
                userTwoCount:7,
                userTwoCrib:0,
                userTwoTotal:7
            },
            {
                userOnePlay:1,
                userOneCount:5,
                userOneCrib:2,
                userOneTotal:8,
                userTwoPlay:0,
                userTwoCount:7,
                userTwoCrib:0,
                userTwoTotal:7
            },
            {
                userOnePlay:1,
                userOneCount:5,
                userOneCrib:2,
                userOneTotal:8,
                userTwoPlay:0,
                userTwoCount:7,
                userTwoCrib:0,
                userTwoTotal:7
            },
            {
                userOnePlay:1,
                userOneCount:5,
                userOneCrib:2,
                userOneTotal:8,
                userTwoPlay:0,
                userTwoCount:7,
                userTwoCrib:0,
                userTwoTotal:7
            }],
        },
            {
            gameid:"4",
            date: 12-31-82,
            userOne: "Dan",
            userTwo:"Chris",
            userOnePlayAvg:3,
            userOneCountAvg:7,
            userOneCribAvg:3.35,
            userTwoPlayAvg:3,
            userTwoCountAvg:7,
            userTwoCribAvg:3.35,
            hands:[
                {
                userOnePlay:1,
                userOneCount:5,
                userOneCrib:2,
                userOneTotal:8,
                userTwoPlay:0,
                userTwoCount:7,
                userTwoCrib:0,
                userTwoTotal:7
            },
            {
                userOnePlay:1,
                userOneCount:5,
                userOneCrib:2,
                userOneTotal:8,
                userTwoPlay:0,
                userTwoCount:7,
                userTwoCrib:0,
                userTwoTotal:7
            },
            {
                userOnePlay:1,
                userOneCount:5,
                userOneCrib:2,
                userOneTotal:8,
                userTwoPlay:0,
                userTwoCount:7,
                userTwoCrib:0,
                userTwoTotal:7
            },
            {
                userOnePlay:1,
                userOneCount:5,
                userOneCrib:2,
                userOneTotal:8,
                userTwoPlay:0,
                userTwoCount:7,
                userTwoCrib:0,
                userTwoTotal:7
            },
            {
                userOnePlay:1,
                userOneCount:5,
                userOneCrib:2,
                userOneTotal:8,
                userTwoPlay:0,
                userTwoCount:7,
                userTwoCrib:0,
                userTwoTotal:7
            },
            {
                userOnePlay:1,
                userOneCount:5,
                userOneCrib:2,
                userOneTotal:8,
                userTwoPlay:0,
                userTwoCount:7,
                userTwoCrib:0,
                userTwoTotal:7
            },
            {
                userOnePlay:1,
                userOneCount:5,
                userOneCrib:2,
                userOneTotal:8,
                userTwoPlay:0,
                userTwoCount:7,
                userTwoCrib:0,
                userTwoTotal:7
            },
            {
                userOnePlay:1,
                userOneCount:5,
                userOneCrib:2,
                userOneTotal:8,
                userTwoPlay:0,
                userTwoCount:7,
                userTwoCrib:0,
                userTwoTotal:7
            },
            {
                userOnePlay:1,
                userOneCount:5,
                userOneCrib:2,
                userOneTotal:8,
                userTwoPlay:0,
                userTwoCount:7,
                userTwoCrib:0,
                userTwoTotal:7
            }
    ]

    }
]

db.GameCard
  .remove({})
  .then(() => db.GameCard.collection.insertMany(gameCardSeed))
  .then(data => {
    console.log(data.result.n + " games inserted!");
    process.exit(0);
  })
  .catch(err => {
    console.error(err);
    process.exit(1);
  });
